version: 0.0
os: linux
files:
  - source: /
    destination: /home/devuser/projects
permissions:
  - object: /home/devuser/projects
    pattern: "**"
    owner: devuser
    group: devuser
hooks:
  ApplicationStop:
    - location: deploy/applicationStop.sh
      timeout: 10
  BeforeInstall:
    - location: deploy/beforeInstall.sh
      timeout: 10
  AfterInstall:
    - location: deploy/afterInstall.sh
      timeout: 500
  ApplicationStart:
    - location: deploy/applicationStart.sh
      timeout: 10
  ValidateService:
    - location: deploy/validateService.sh
      timeout: 10